name: Auto ClockIn
on:
  schedule:
    - cron:  '38 21 * * *'
  workflow_dispatch: 
jobs:
  ClockIn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: update libc
      run: sudo apt install libc6 libc-bin
    - name: ClockIn for Etiger
      run: ./Tools/Tool Etiger 18117121393 LangNing0117 ClockIn
    - name: ClockIn for Luogu
      run: ./Tools/Tool Luogu langningc2009 1\!2@3#qQwWeE ClockIn
