name: C++ Auto Compile
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Send mail when starts
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.office365.com
        server_port: 587
        username: ${{ secrets.MAILUSERNAME }}
        password: ${{ secrets.MAILPASSWORD }}
        subject: Action Runs Start
        body: Action Runs Start, Tips From Github Actions
        from: ${{ secrets.MAILUSERNAME }}
        to: ${{ secrets.MAILUSERNAME }}
    - name: Run
      run: ./Tools/DoAutoCompileWorks
    - name: Send mail when ends
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.office365.com
        server_port: 587
        username: ${{ secrets.MAILUSERNAME }}
        password: ${{ secrets.MAILPASSWORD }}
        subject: Action Runs End
        body: file://mail.txt
        from: ${{ secrets.MAILUSERNAME }}
        to: ${{ secrets.MAILUSERNAME }}
    - name: Upload Artifact 1
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Etiger
        path: Etiger.zip
    - name: Upload Artifact 2
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Luogu
        path: Luogu.zip
