name: C++ Auto Compile
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install openssl
      run: |
        wget https://www.openssl.org/source/openssl-3.0.5.tar.gz
        tar -zxf openssl-3.0.5.tar.gz
        rm openssl-3.0.5.tar.gz
        cd ./openssl-3.0.5/
        ./config
        make
        make test
        sudo make install
        cd ../
        rm -f -r ./openssl-3.0.5/
    - name: Install libcurl
      run: |
        wget https://curl.se/download/curl-7.85.0.tar.gz
        tar -zxf curl-7.85.0.tar.gz
        rm curl-7.85.0.tar.gz
        cd ./curl-7.85.0/
        ./configure --with-openssl
        make
        make test
        sudo make install
        cd ../
        rm -f -r ./curl-7.85.0/
    - name: Install libjpeg
      run: |
        wget http://www.ijg.org/files/jpegsrc.v9e.tar.gz
        tar -zxf jpegsrc.v9e.tar.gz
        rm jpegsrc.v9e.tar.gz
        cd ./jpeg-9e/
        ./configure
        make
        make test
        sudo make install
        cd ../
        rm -f -r ./jpeg-9e/
    - name: Send mail when starts
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.office365.com
        server_port: 587
        username: ${{ secrets.MAILUSERNAME }}
        password: ${{ secrets.MAILPASSWORD }}
        subject: Action Runs Start
        body: Action Runs Start, Tips From Github Actions
        from: ${{ secrets.MAILUSERNAME }}
        to: ${{ secrets.MAILUSERNAME }}
    - name: Run
      run: ./Tools/DoAutoCompileWorks
    - name: Send mail when ends
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.office365.com
        server_port: 587
        username: ${{ secrets.MAILUSERNAME }}
        password: ${{ secrets.MAILPASSWORD }}
        subject: Action Runs End
        body: file://mail.txt
        from: ${{ secrets.MAILUSERNAME }}
        to: ${{ secrets.MAILUSERNAME }}
    - name: Upload Artifact 1
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Etiger
        path: Etiger.zip
    - name: Upload Artifact 2
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Luogu
        path: Luogu.zip
