name: C++ Auto Compile
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Send mail
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.office365.com
        server_port: 587
        username: ${{ secrets.MAILUSERNAME }}
        password: ${{ secrets.MAILPASSWORD }}
        subject: testsubject
        body: testbody
        to: langningc2009@163.com
        from: GitHub Actions
    - name: Run
      run: ./DoAutoCompileWorks