name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: config1
      run: git config --global user.email "langningc2009@163.com"
    - name: config2
      run: git config --global user.name "ChenLangNing"
    - name: config3
      run: git config pull.rebase false
    - name: compile
      run: for i in "."/*.cpp; do echo $i; gcc "$i" -o "${i%*".cpp"}.exe" -std=c++11 -lm -lstdc++; git add "${i%*".cpp"}.exe"; done
    - name: commit
      run: git commit -a -m "no message"
    - name: push
      run: git push
    - name: pull
      run: git pull
